import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [313]:
df = pd.read_csv('C://Users//HP//Downloads//spaceship-titanic//train.csv')

In [314]:
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [315]:
df.tail()

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True

In [316]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [317]:
df.shape

(8693, 14)

In [318]:
df = df.loc[:, ['HomePlanet', 'Age','VIP', 'Transported']]
df

HomePlanet   Age    VIP  Transported
0        Europa  39.0  False        False
1         Earth  24.0  False         True
2        Europa  58.0   True        False
3        Europa  33.0  False        False
4         Earth  16.0  False         True
...         ...   ...    ...          ...
8688     Europa  41.0   True        False
8689      Earth  18.0  False        False
8690      Earth  26.0  False         True
8691     Europa  32.0  False        False
8692     Europa  44.0  False         True

[8693 rows x 4 columns]

In [319]:
df.isna().sum()

HomePlanet     201
Age            179
VIP            203
Transported      0
dtype: int64

In [320]:
df = df.loc[df.HomePlanet.notna(),['HomePlanet', 'Age','VIP', 'Transported']]
df

HomePlanet   Age    VIP  Transported
0        Europa  39.0  False        False
1         Earth  24.0  False         True
2        Europa  58.0   True        False
3        Europa  33.0  False        False
4         Earth  16.0  False         True
...         ...   ...    ...          ...
8688     Europa  41.0   True        False
8689      Earth  18.0  False        False
8690      Earth  26.0  False         True
8691     Europa  32.0  False        False
8692     Europa  44.0  False         True

[8492 rows x 4 columns]

In [321]:
df = df.loc[df.Age.notna(),['HomePlanet', 'Age','VIP','Transported']]
df

HomePlanet   Age    VIP  Transported
0        Europa  39.0  False        False
1         Earth  24.0  False         True
2        Europa  58.0   True        False
3        Europa  33.0  False        False
4         Earth  16.0  False         True
...         ...   ...    ...          ...
8688     Europa  41.0   True        False
8689      Earth  18.0  False        False
8690      Earth  26.0  False         True
8691     Europa  32.0  False        False
8692     Europa  44.0  False         True

[8315 rows x 4 columns]

In [322]:
df = df.loc[ df.VIP.notna(),['HomePlanet', 'Age','VIP', 'Transported']]
df

HomePlanet   Age    VIP  Transported
0        Europa  39.0  False        False
1         Earth  24.0  False         True
2        Europa  58.0   True        False
3        Europa  33.0  False        False
4         Earth  16.0  False         True
...         ...   ...    ...          ...
8688     Europa  41.0   True        False
8689      Earth  18.0  False        False
8690      Earth  26.0  False         True
8691     Europa  32.0  False        False
8692     Europa  44.0  False         True

[8121 rows x 4 columns]

In [323]:
df.isna().sum()

HomePlanet     0
Age            0
VIP            0
Transported    0
dtype: int64

In [324]:
df.head()

HomePlanet   Age    VIP  Transported
0     Europa  39.0  False        False
1      Earth  24.0  False         True
2     Europa  58.0   True        False
3     Europa  33.0  False        False
4      Earth  16.0  False         True

In [325]:
# first lets predict usuing only one feature 
feat_col = ['Age']
X = df[feat_col]
y = df.Transported

In [326]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [327]:
from sklearn.model_selection import cross_val_score

In [328]:
cross_val_score(lr, X,y, cv=5, scoring='accuracy').mean()

0.5221055702917772

In [329]:
y.value_counts(normalize=True)

True     0.503386
False    0.496614
Name: Transported, dtype: float64

In [330]:
df.head()

HomePlanet   Age    VIP  Transported
0     Europa  39.0  False        False
1      Earth  24.0  False         True
2     Europa  58.0   True        False
3     Europa  33.0  False        False
4      Earth  16.0  False         True

In [331]:
from sklearn.preprocessing import OneHotEncoder

In [332]:
ohe = OneHotEncoder(handle_unknown = 'ignore', sparse=False)

In [333]:
ohe.fit_transform(df[['HomePlanet']])

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [334]:
ohe.categories_

[array(['Earth', 'Europa', 'Mars'], dtype=object)]

In [335]:
ohe.fit_transform(df[['VIP']])

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [336]:
ohe.categories_

[array([False, True], dtype=object)]

In [337]:
X = df.drop('Transported', axis='columns')

In [338]:
X.head()

HomePlanet   Age    VIP
0     Europa  39.0  False
1      Earth  24.0  False
2     Europa  58.0   True
3     Europa  33.0  False
4      Earth  16.0  False

In [339]:
from sklearn.compose import make_column_transformer
# We use col trans whenever we need to preprocessing our data

In [340]:
col_trans = make_column_transformer(
    (OneHotEncoder(), ['HomePlanet','VIP']),
    remainder='passthrough')


In [341]:
col_trans.fit_transform(X)

array([[ 0.,  1.,  0.,  1.,  0., 39.],
       [ 1.,  0.,  0.,  1.,  0., 24.],
       [ 0.,  1.,  0.,  0.,  1., 58.],
       ...,
       [ 1.,  0.,  0.,  1.,  0., 26.],
       [ 0.,  1.,  0.,  1.,  0., 32.],
       [ 0.,  1.,  0.,  1.,  0., 44.]])

In [342]:
from sklearn.pipeline import make_pipeline

In [343]:
pipe = make_pipeline(col_trans, lr)

In [344]:
cross_val_score(pipe, X,y, cv=5, scoring='accuracy').mean()
#adding these 2 features our accuracy increases

0.6034957180750284

In [345]:
pipe.fit(X,y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['HomePlanet', 'VIP'])])),
                ('logisticregression', LogisticRegression())])

In [346]:
df_test = pd.read_csv('C://Users//HP//Downloads//spaceship-titanic//test.csv')
df_test.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [347]:
df_test.dropna(inplace=True)

In [350]:
feature_col = ['HomePlanet', 'Age','VIP']
X_new = df_test[feature_col]

In [351]:
X_new 

HomePlanet   Age    VIP
0         Earth  27.0  False
1         Earth  19.0  False
2        Europa  31.0  False
3        Europa  38.0  False
4         Earth  20.0  False
...         ...   ...    ...
4269      Earth  43.0  False
4270       Mars  43.0  False
4271      Earth  40.0  False
4272      Earth  34.0  False
4276      Earth  43.0  False

[3281 rows x 3 columns]

In [352]:
y_pred = pipe.predict(X_new)

In [293]:
y_pred

array([False, False,  True, ..., False, False, False])

In [304]:
y_pred.shape

(3281,)

In [305]:
 df['PassengerId'].shape

(4277,)

In [354]:
# Lets save our predicted values in csv formate
np.genfromtxt('C:/Users/HP/Downloads/spaceship/y_pred.csv', delimiter=',')

array([0., 0., 1., ..., 0., 0., 0.])

In [ ]:
C:/Users/HP/Downloads/spaceship/y_pred.csv
pd.DataFrame(X_train.columns).to_csv("feature_list.csv", index = None)